"""empty message

Revision ID: efec55e15113
Revises: 9202af9efa9b
Create Date: 2024-05-28 13:17:10.453894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efec55e15113'
down_revision = '9202af9efa9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doses')
    op.drop_table('medicines')
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diary_log', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diary_entries', schema=None) as batch_op:
        batch_op.drop_column('diary_log')

    op.create_table('medicines',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='medicines_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('doses',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('med_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dose', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('time', mysql.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['med_id'], ['medicines.id'], name='doses_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
